### PR TITLE
Adds OSS dm and removes fixed versions

### PR DESCRIPTION
**Pull request by joaofreitas-qubit**
Relates with: #qubIT-Omnis-4736

### CODE REVIEW

**Review by joaojtmarques-qubit — APPROVED** [review]

**Review by joaojtmarques-qubit — CHANGES_REQUESTED** [review]
Remove distributionManagement and repositories tags

**Comment by joaofreitas-qubit** [comment]
> Remove distributionManagement and repositories tags

i can't because the parent does not have the same distribution management

**Review by pabrantes — APPROVED** [review]

**Comment by pabrantes** [comment]
> > Remove distributionManagement and repositories tags
> 
> i can't because the parent does not have the same distribution management

What we can think (but not a priority) is to create a child of the qub-fenixedu-oproject, called qub-fenixedu-ulisboa-project to define ULisboa's repos. With this hierarachy we could change the ULisboa's repositories in a single point when/if needed. We can open a task for that but I wouldn't say it's currently a priority.

**Comment by joaofreitas-qubit** [comment]
> > > Remove distributionManagement and repositories tags
> > 
> > 
> > i can't because the parent does not have the same distribution management
> 
> What we can think (but not a priority) is to create a child of the qub-fenixedu-oproject, called qub-fenixedu-ulisboa-project to define ULisboa's repos. With this hierarachy we could change the ULisboa's repositories in a single point when/if needed. We can open a task for that but I wouldn't say it's currently a priority.

I will create an issue for that in dev

**Review by joaojtmarques-qubit — APPROVED** [review]

**Pull request merged**
